[package]
name = "rsa"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
num-integer = "0.1"
rand = "0.8"

[lib]
path = "src/lib.rs"

[dev-dependencies]
quickcheck = "1.0"
