[package]
name = "Twofish"
version = "0.1.0"
edition = "2024"

[lib]
name = "twofish"
path = "src/lib.rs"

[dependencies]
symmetric_cipher = { path = "../symmetric_cipher" }
tokio = "1.45.0"
rand = "0.9.1"
